# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mongo
#     environment:
#       - MONGODB_URI=mongodb://mongo:27017/zomato_clone

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/zomato_clone
    restart: unless-stopped    # <-- auto restart container unless explicitly stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped    # <-- auto restart container unless explicitly stopped

volumes:
  mongo_data:
