name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Prepare folder on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "rm -rf food-app && mkdir food-app"

      - name: Copy files to EC2
        run: |
          scp -i ec2_key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/food-app

      - name: Deploy on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd food-app

            echo "Pulling latest changes and rebuilding services..."
            docker-compose pull
            docker-compose build

            echo "Stopping existing services..."
            docker-compose down

            echo "Starting services..."
            docker-compose up -d

            echo "Waiting for services to start..."
            sleep 10

            echo "Running database seed..."
            docker-compose run --rm app node scripts/seedDatabase.js

            echo "Checking container status..."
            docker ps

            echo "Checking app logs..."
            docker logs food-app

            echo "Testing app accessibility..."
            curl -v http://localhost:3000

            echo "Container information:"
            docker inspect food-app

            echo "Cleaning up any unused resources in the background..."
            docker system prune -f &
          EOF
